# Generated by Django 3.0 on 2019-12-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Snippet',
        ),
    ]
