# Generated by Django 3.0 on 2019-12-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191213_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='description',
        ),
    ]
