# Generated by Django 3.0 on 2019-12-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_snippet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
