# Generated by Django 3.0 on 2019-12-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191213_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='description',
            field=models.CharField(default='Desc', max_length=255),
        ),
    ]
