# Generated by Django 3.0 on 2019-12-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191213_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='description',
        ),
    ]
